export const quotes = [
    "Believe you can and you're halfway there.",
    "The only way to achieve the impossible is to believe it is possible.",
    "You are stronger than you think.",
    "Every day is a second chance.",
    "Don't watch the clock; do what it does. Keep going.",
    "You are capable of amazing things.",
    "Stay positive, work hard, make it happen.",
    "The best way to predict the future is to create it.",
    "You are your only limit.",
    "Believe in yourself and all that you are.",
    "Your only limit is your mind.",
    "Push yourself, because no one else is going to do it for you.",
    "Success is not for the lazy.",
    "Dream it. Wish it. Do it.",
    "Stay focused and never give up.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "Don't stop until you're proud.",
    "Difficult roads often lead to beautiful destinations.",
    "Believe in the power of yet.",
    "You are enough just as you are.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Don't wait for opportunity. Create it.",
    "Success doesn't come from what you do occasionally, it comes from what you do consistently.",
    "Believe in yourself and you will be unstoppable.",
    "You are capable of more than you know.",
    "The future depends on what you do today.",
    "You don't have to be perfect to be amazing.",
    "Believe in your dreams and they may come true; believe in yourself and they will come true.",
    "You are stronger than you know.",
    "The best time for new beginnings is now."
];
